#!/usr/bin/env perl
use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/../lib";
use lib "$FindBin::Bin/lib";
use Data::Dumper;
use OptArgs2;

cmd 'App::job' => (
    comment => 'a job management tool',
    optargs => sub {

        arg command => (
            isa      => 'SubCmd',
            comment  => 'action to take',
            fallback => (
                name    => 'fallback',
                isa     => 'Str',
                comment => 'the fallback argument',
            ),
        );

        opt help => (
            isa     => 'Bool',
            comment => 'print a help message and exit',
            alias   => 'h',
            default => 0,
            ishelp  => 1,
        );

        opt quiet => (
            isa     => 'Bool',
            alias   => 'q',
            default => 0,
            comment => 'output nothing while working',
        );

        opt usage => (
            isa     => 'Bool',
            alias   => 'u',
            comment => 'display usage tree',
            hidden  => 1,
        );
    },
);

subcmd 'App::job::start' => (
    comment => 'start a job',
    optargs => sub {

        arg job => (
            isa      => 'Str',
            comment  => 'job to start',
            required => 1,
        );
    },
);

subcmd 'App::job::stop' => (
    comment => 'stop a job',
    optargs => sub {

        arg job => (
            isa      => 'Str',
            comment  => 'job to stop',
            required => 1,
        );
    },
);

subcmd 'App::job::usage' => ( comment => 'print the command usage tree', );

my ( $class, $opts ) = class_optargs('App::job');
$class->new->run($opts);

