#!/usr/bin/env perl
use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/../lib";
use lib "$FindBin::Bin/lib";
use Data::Dumper;
use OptArgs2;

cmd 'App::job' => (
    comment => 'a job management tool',
    abbrev  => 1,
    optargs => sub {

        arg command => (
            isa      => 'SubCmd',
            comment  => 'action to take, one of:',
            required => 1,
        );

        opt help => (
            isa     => 'Flag',
            comment => 'print a help message and exit',
            alias   => 'h',
            trigger => sub { die shift->usage(OptArgs2::STYLE_FULL) },
        );

        opt quiet => (
            isa     => 'Flag',
            alias   => 'q',
            comment => 'output nothing while working',
        );

        opt usage => (
            isa     => 'Flag',
            alias   => 'u',
            comment => 'display usage tree',
            hidden  => 1,
            trigger => sub { die shift->usage_tree }
        );
    },
);

subcmd 'App::job::start' => (
    comment => 'start a job',
    optargs => sub {

        arg job => (
            isa      => 'Str',
            comment  => 'job to start',
            required => 1,
        );

        opt opt1 => (
            isa     => 'Str',
            alias   => 'o',
            default => 'stuff',
            comment => 'a string option',
        );

    },
);

subcmd 'App::job::stop' => (
    comment => 'stop a job',
    optargs => sub {

        arg job => (
            isa      => 'Str',
            comment  => 'job to stop',
            required => 1,
        );

        opt opt2 => (
            isa      => 'ArrayRef',
            isa_name => 'X',
            alias    => 'p',
            comment  => 'a string option with name',
        );

    },
);

my ( $class, $opts ) = cmd_optargs('App::job');
print $class. ' ' . Dumper($opts);
