#!/usr/bin/env perl
use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/../lib";
use lib "$FindBin::Bin/lib";
use Data::Dumper;
use OptArgs2;

cmd 'App::job' => (
    comment => 'a job management tool',
    optargs => sub {

        arg command => (
            isa      => 'SubCmd',
            comment  => 'action to take, one of:',
            fallback => {
                name    => 'fallback',
                isa     => 'Str',
                hidden  => 1,
                comment => 'the fallback argument',
            },
        );

        #        arg other => (
        #            isa      => 'Str',
        #            comment  => 'action to take',
        #            required => 1,
        #        );

        opt help => (
            isa     => 'Bool',
            comment => 'print a help message and exit',
            alias   => 'h',
            default => 0,
            ishelp  => 1,
        );

        opt quiet => (
            isa     => 'Bool',
            alias   => 'q',
            default => 0,
            comment => 'output nothing while working',
        );

        opt usage => (
            isa     => 'Bool',
            alias   => 'u',
            comment => 'display usage tree',
            hidden  => 1,
        );
    },
);

subcmd 'App::job::start' => (
    comment => 'start a job',
    optargs => sub {

        arg job => (
            isa      => 'Str',
            comment  => 'job to start',
            required => 1,
        );

        opt opt1 => (
            isa     => 'Str',
            alias   => 'o',
            default => 'stuff',
            comment => 'a string option',
        );

    },
);

subcmd 'App::job::stop' => (
    comment => 'stop a job',
    optargs => sub {

        arg job => (
            isa      => 'Str',
            comment  => 'job to stop',
            required => 1,
        );

        opt opt2 => (
            isa      => 'ArrayRef',
            isa_name => 'X',
            alias    => 'p',
            comment  => 'a string option with name',
        );

    },
);

my ( $class, $opts ) = class_optargs('App::job');
if ( exists $opts->{usage} && $opts->{usage} ) {
    print OptArgs2::get_cmd($class)->usage_tree;
}
else {
    print $class. ' ' . Dumper($opts);
}

#eval "require $class" or die $@;
#$class->new->run($opts);

