#!/bin/bash
set -e

mkdir -p lib/Getopt

sed \
    -e 's/Getopt::Args/GETOPT::ARGS/g' \
    -e 's/OptArgs/Getopt::Args/g' \
    -e 's/p5-Getopt::Args/p5-OptArgs/g' \
    -e 's/GETOPT::ARGS/OptArgs/g' \
    lib/OptArgs.pm > lib/Getopt/Args.pm

podtidy --inplace --nobackup `cat .podtidy-opts` lib/Getopt/Args.pm
