---
abstract: 'CLI argument and option processing'
author:
  - 'Mark Lawrence <nomad@null.net>'
build_requires:
  ExtUtils::MakeMaker: '0'
  IO::Capture::Stdout: '0'
  POSIX: '0'
  Test::Fatal: '0'
  Test::More: '0'
  Test::Output: '0'
configure_requires:
  ExtUtils::MakeMaker::CPANfile: '0.09'
  File::Spec: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.64, CPAN::Meta::Converter version 2.150010'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: OptArgs
no_index:
  directory:
    - t
    - inc
  package:
    - OptArgs::Usage
    - Getopt::Args::Usage
requires:
  Carp: '0'
  Encode: '2.24'
  Exporter::Tidy: '0'
  File::Which: '0'
  Getopt::Long: '2.37'
  I18N::Langinfo: '0'
  List::Util: '0'
  Text::Abbrev: '0'
  perl: '5.006'
resources:
  repository: ssh://git@github.com/mlawren/p5-OptArgs.git
version: v0.1.21
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
