---
abstract: 'CLI argument and option processing'
author:
  - 'Mark Lawrence <nomad@null.net>'
build_requires:
  ExtUtils::MakeMaker: '0'
  IO::Capture::Stdout: '0'
  POSIX: '0'
  Test2::V0: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
  ExtUtils::MakeMaker::CPANfile: '0.08'
  File::Spec: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: OptArgs2
no_index:
  directory:
    - t
    - inc
  package:
    - OptArgs2::Arg
    - OptArgs2::Cmd
    - OptArgs2::Fallback
    - OptArgs2::Mo
    - OptArgs2::Opt
    - OptArgs2::Result
    - OptArgs2::Util
    - Getopt::Args2::Arg
    - Getopt::Args2::Cmd
    - Getopt::Args2::Fallback
    - Getopt::Args2::Mo
    - Getopt::Args2::Opt
    - Getopt::Args2::Result
    - Getopt::Args2::Util
requires:
  Carp: '0'
  Encode: '2.24'
  Getopt::Long: '2.37'
  I18N::Langinfo: '0'
  List::Util: '0'
  Text::Abbrev: '0'
  perl: '5.01'
resources:
  repository: ssh://git@github.com/mlawren/p5-OptArgs2.git
version: v0.0.12_1
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
