---
abstract: 'CLI argument and option processing'
author:
  - 'Mark Lawrence <nomad@null.net>'
build_requires:
  Capture::Tiny: '0'
  ExtUtils::MakeMaker: '0'
  POSIX: '0'
  Test2::V0: '0'
configure_requires:
  ExtUtils::MakeMaker::CPANfile: '0.09'
  File::Spec: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.64, CPAN::Meta::Converter version 2.150010'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: OptArgs2
no_index:
  directory:
    - t
    - inc
  package:
    - OptArgs2::Arg
    - OptArgs2::CODEREF
    - OptArgs2::Cmd
    - OptArgs2::CmdBase
    - OptArgs2::Opt
    - OptArgs2::OptArgBase
    - OptArgs2::Status
    - OptArgs2::SubCmd
requires:
  Carp: '0'
  Encode::Locale: '0'
  Exporter::Tidy: '0'
  File::Which: '0'
  Getopt::Long: '2.37'
  List::Util: '0'
  Term::Size::Perl: '0'
  Text::Abbrev: '0'
  perl: '5.016'
resources:
  bugtracker: https://github.com/mlawren/p5-OptArgs/issues
  homepage: https://github.com/mlawren/p5-OptArgs
  repository: ssh://git@github.com/mlawren/p5-OptArgs.git
version: v2.0.15
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
