# Generated by Class::Inline version 0.0.1
# Date: Thu Sep 15 15:41:54 2022
package OptArgs2::Pager_CI;    ## CI_PM_FILTER
#<<<
use Class::Inline::Check <<'CI_PM_FILTER'; ## CI_PM_FILTER
use strict;use warnings;package OptArgs2::Pager_CI;our$INLINE;
sub import {$INLINE=exists $_[1]->{'has'}? $_[1]: {has=>$_[1]}}package
OptArgs2::Pager;our%_ATTRS;require Carp;my%_BUILD_CHECK;
sub new {my$class=shift;my$self={@_ ? @_ > 1 ? @_ : %{$_[0]}: ()};%_ATTRS=map
{($_=>1)}keys %$self;bless$self,ref$class || $class;$_BUILD_CHECK{$class}//=
do {my@possible=($class);my@BUILD;my@CHECK;while (@possible){no strict 'refs';
my$c=shift@possible;push@BUILD,*{$c .'::BUILD'}if exists &{$c .'::BUILD'};push
@CHECK,*{$c .'::__CHECK'}if exists &{$c .'::__CHECK'};push@possible,@{$c .
'::ISA'}}[reverse(@CHECK),reverse(@BUILD)]};map {$self->$_}@{$_BUILD_CHECK{
$class}};Carp::carp("OptArgs2::Pager attribute '$_' unexpected")for keys
%_ATTRS;$self}
sub __CHECK {no strict 'refs';my$_attrs=*{ref($_[0]).'::_ATTRS'};map {delete
$_attrs->{$_}}keys %{$INLINE->{'has'}}}
sub auto {$_[0]->__RO($_[1])if @_ > 1;$_[0]{'auto'}//= $INLINE->{'has'}->{
'auto'}->{'default'}}
sub encoding {$_[0]->__RO($_[1])if @_ > 1;$_[0]{'encoding'}//= $INLINE->{'has'
}->{'encoding'}->{'default'}}
sub fh {if (@_ > 1){$_[0]{'fh'}=$_[1];return $_[0]}$_[0]{'fh'}//= $INLINE->{
'has'}->{'fh'}->{'default'}->($_[0])}
sub orig_fh {$_[0]->__RO($_[1])if @_ > 1;$_[0]{'orig_fh'}//= $INLINE->{'has'}
->{'orig_fh'}->{'default'}->($_[0])}
sub pager {$_[0]->__RO($_[1])if @_ > 1;$_[0]{'pager'}//= $INLINE->{'has'}->{
'pager'}->{'default'}->($_[0])}
sub pid {if (@_ > 1){$_[0]{'pid'}=$_[1];return $_[0]}$_[0]{'pid'}}
sub __RO {my (undef,undef,undef,$sub)=caller(1);Carp::croak(
"attribute $sub is read-only")}
sub _dump {my$self=shift;my$d=shift // 1;require Data::Dumper;no warnings
'once';local$Data::Dumper::Indent=1;local$Data::Dumper::Maxdepth=$d;local
$Data::Dumper::Sortkeys=1;my$x=Data::Dumper::Dumper($self);$x =~ s/.*?{/{/;$x
=~ s/}.*?\n$/}/;Carp::carp($self .' '.$x ."\n ")}$INC{'OptArgs2/Pager.pm'}=
__FILE__;
CI_PM_FILTER
#>>>
1;
